### ISSUE TITLE
when include user in the topic interface, error happens

### ISSUE THREAD

**Issue by wdwyjw** [NauxLiu/phphub-server#24]
但是我发现当访问topics时如果include了user就会抛出下面的异常。
v1/topics?include=node,last_reply_user,user&filters=excellent&per_page=20&page=1&columns=user(signature)

{
  "debug" : {
    "trace" : [
      "#0 [internal function]: Illuminate\\Database\\Query\\Builder->__call('avatar', Array)",
      "#1 [internal function]: Illuminate\\Database\\Query\\Builder->avatar()",
      "#2 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(949): call_user_func_array(Array, Array)",
      "#3 [internal function]: Illuminate\\Database\\Eloquent\\Builder->__call('avatar', Array)",
      "#4 [internal function]: Illuminate\\Database\\Eloquent\\Builder->avatar()",
      "#5 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3499): call_user_func_array(Array, Array)",
      "#6 /var/www/phphub-server/app/Transformers/UserTransformer.php(24): Illuminate\\Database\\Eloquent\\Model->__call('avatar', Array)",
      "#7 /var/www/phphub-server/app/Transformers/UserTransformer.php(24): PHPHub\\User->avatar()",
      "#8 /var/www/phphub-server/app/Transformers/BaseTransformer.php(21): PHPHub\\Transformers\\UserTransformer->transformData(Object(PHPHub\\User))",
      "#9 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(338): PHPHub\\Transformers\\BaseTransformer->transform(Object(PHPHub\\User))",
      "#10 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(278): League\\Fractal\\Scope->fireTransformer(Object(PHPHub\\Transformers\\UserTransformer), Object(PHPHub\\User))",
      "#11 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(208): League\\Fractal\\Scope->executeResourceTransformers()",
      "#12 /var/www/phphub-server/vendor/league/fractal/src/TransformerAbstract.php(151): League\\Fractal\\Scope->toArray()",
      "#13 /var/www/phphub-server/vendor/league/fractal/src/TransformerAbstract.php(124): League\\Fractal\\TransformerAbstract->includeResourceIfAvailable(Object(League\\Fractal\\Scope), Object(PHPHub\\Topic), Array, 'user')",
      "#14 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(363): League\\Fractal\\TransformerAbstract->processIncludedResources(Object(League\\Fractal\\Scope), Object(PHPHub\\Topic))",
      "#15 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(342): League\\Fractal\\Scope->fireIncludedTransformers(Object(PHPHub\\Transformers\\TopicTransformer), Object(PHPHub\\Topic))",
      "#16 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(281): League\\Fractal\\Scope->fireTransformer(Object(PHPHub\\Transformers\\TopicTransformer), Object(PHPHub\\Topic))",
      "#17 /var/www/phphub-server/vendor/league/fractal/src/Scope.php(208): League\\Fractal\\Scope->executeResourceTransformers()",
      "#18 /var/www/phphub-server/app/Transformers/IncludeManager/TransformerAdapter.php(42): League\\Fractal\\Scope->toArray()",
      "#19 /var/www/phphub-server/vendor/dingo/api/src/Transformer/Factory.php(87): PHPHub\\Transformers\\IncludeManager\\TransformerAdapter->transform(Object(Illuminate\\Pagination\\LengthAwarePaginator), Object(PHPHub\\Transformers\\TopicTransformer), Object(Dingo\\Api\\Transformer\\Binding), Object(Dingo\\Api\\Http\\Request))",
      "#20 /var/www/phphub-server/vendor/dingo/api/src/Http/Response.php(95): Dingo\\Api\\Transformer\\Factory->transform(Object(Illuminate\\Pagination\\LengthAwarePaginator))",
      "#21 /var/www/phphub-server/vendor/dingo/api/src/Routing/Router.php(596): Dingo\\Api\\Http\\Response->morph('json')",
      "#22 /var/www/phphub-server/vendor/dingo/api/src/Routing/Router.php(567): Dingo\\Api\\Routing\\Router->prepareResponse(Object(Dingo\\Api\\Http\\Response), Object(Dingo\\Api\\Http\\Request), 'json')",
      "#23 /var/www/phphub-server/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#24 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#25 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#26 /var/www/phphub-server/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#27 [internal function]: LucaDegasperi\\OAuth2Server\\Middleware\\OAuthExceptionHandlerMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#28 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#29 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#30 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#31 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#32 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#33 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#34 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#35 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#36 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#37 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#38 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#39 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#40 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#41 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#42 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#43 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#44 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#45 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#46 /var/www/phphub-server/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#47 /var/www/phphub-server/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
      "#48 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
      "#49 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#50 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
      "#51 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
      "#52 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#53 /var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
      "#54 /var/www/phphub-server/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
      "#55 {main}"
    ],
    "file" : "/var/www/phphub-server/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
    "class" : "BadMethodCallException",
    "line" : 2093
  },
  "status_code" : 500,
  "message" : "Call to undefined method Illuminate\\Database\\Query\\Builder::avatar()"
}

**Comment by remxcode** [comment]
#22
